### ISSUE TITLE
Great! How's the results?

### ISSUE THREAD

**Issue by hunkim** [andabi/deep-text-corrector#1]
I was wondering which one works the best. Thanks in advance.

```
First trial: seq2seq w/ attention + nucle 2.3 dataset
Next..
more data, data augmentations, ...
tweeking (tweaking) nets like Bytenet or Transformer 
beam search
```

**Comment by andabi** [comment]
@hunkim The results was in fact not so successful. even though we have other ideas in mind and more datasets, we didn't try those yet haha..

**Comment by hunkim** [comment]
Thanks!

**Comment by andabi** [comment]
@hunkim when i make a progress, i'll let you know. thanks for your interest ;)

**Comment by andabi** [comment]
@hunkim i made a mistake. The results was not so successful.
